
const HOY = '2026-04-20';

const PLANTAS = [
  {
    id: 1,
    img: 'img/phalaenopsis-pequenas.jpg',
    emoji: '🌸',
    nombre: 'Phalaenopsis x2 pequeñas',
    tipo: 'Orquídea',
    familia: 'Orchidaceae',
    estado: 'atencion',
    riegoDias: 8,
    ultimoRiego: '2026-04-20',
    humedad: 60,
    altura: 25,
    diametro: 12,
    temp: 21,
    luz: 50,
    ubicacion: 'Interior',
    plantada: '2025-01-01',
    diagnosis: [
      { tipo: 'agua', titulo: 'Revisar humedad', valor: 55, nota: 'Próximo riego en 8 días', sev: 'mid' },
      { tipo: 'luz', titulo: 'Luz indirecta', valor: 50, nota: 'Sin luz directa. Correcto.', sev: 'low' },
    ],
    notas: 'Dos plantas pequeñas. Requieren atención.',
  },
  {
    id: 2,
    img: 'img/phalaenopsis-blanca.jpg',
    emoji: '🌸',
    nombre: 'Phalaenopsis blanca grande',
    tipo: 'Orquídea',
    familia: 'Orchidaceae',
    estado: 'floreciendo',
    riegoDias: 8,
    ultimoRiego: '2026-04-20',
    humedad: 62,
    altura: 55,
    diametro: 20,
    temp: 21,
    luz: 50,
    ubicacion: 'Interior',
    plantada: '2024-02-14',
    diagnosis: [
      { tipo: 'agua', titulo: 'Humedad óptima', valor: 70, nota: 'Próximo riego en 8 días', sev: 'low' },
      { tipo: 'luz', titulo: 'Luz indirecta', valor: 50, nota: 'Sin luz directa. Correcto.', sev: 'low' },
    ],
    notas: 'Bien, en plena floración.',
  },
  {
    id: 3,
    img: 'img/monstera.jpg',
    emoji: '🍃',
    nombre: 'Monstera deliciosa',
    tipo: 'Tropical',
    familia: 'Araceae',
    estado: 'atencion',
    riegoDias: 8,
    ultimoRiego: '2026-04-20',
    humedad: 62,
    altura: 80,
    diametro: 45,
    temp: 22,
    luz: 65,
    ubicacion: 'Interior',
    plantada: '2023-05-20',
    diagnosis: [
      { tipo: 'agua', titulo: 'Bien hidratada', valor: 75, nota: 'Próximo riego en 8 días', sev: 'low' },
      { tipo: 'luz', titulo: 'Luz indirecta brillante', valor: 65, nota: 'Revisar puntas de hojas', sev: 'mid' },
    ],
    notas: 'Atención en puntas de las hojas.',
  },
  {
    id: 4,
    img: 'img/espatifilo.jpg',
    emoji: '🌿',
    nombre: 'Espatifilo',
    tipo: 'Tropical',
    familia: 'Araceae',
    estado: 'bien',
    riegoDias: 7,
    ultimoRiego: '2026-04-20',
    humedad: 60,
    altura: 40,
    diametro: 25,
    temp: 20,
    luz: 30,
    ubicacion: 'Interior',
    plantada: '2023-09-01',
    diagnosis: [
      { tipo: 'agua', titulo: 'Humedad adecuada', valor: 70, nota: 'Próximo riego en 7 días', sev: 'low' },
      { tipo: 'luz', titulo: 'Poca luz', valor: 30, nota: 'Tolera poca luz', sev: 'low' },
    ],
    notas: 'En buen estado.',
  },
  {
    id: 5,
    img: 'img/aloe-grande.jpg',
    emoji: '🌵',
    nombre: 'Aloe vera grande',
    tipo: 'Suculenta',
    familia: 'Asphodelaceae',
    estado: 'floreciendo',
    riegoDias: 15,
    ultimoRiego: '2026-04-20',
    humedad: 25,
    altura: 60,
    diametro: 40,
    temp: 22,
    luz: 90,
    ubicacion: 'Terraza sur',
    plantada: '2022-03-10',
    diagnosis: [
      { tipo: 'agua', titulo: 'Nivel correcto', valor: 70, nota: 'Próximo riego en 15 días', sev: 'low' },
      { tipo: 'luz', titulo: 'Sol directo', valor: 90, nota: 'Condiciones ideales', sev: 'low' },
    ],
    notas: 'Bien, en floración. Tiene hijuelos para separar.',
  },
  {
    id: 6,
    img: 'img/aloe-pequeno.jpg',
    emoji: '🌵',
    nombre: 'Aloe vera pequeño',
    tipo: 'Suculenta',
    familia: 'Asphodelaceae',
    estado: 'trasplantado',
    riegoDias: 15,
    ultimoRiego: '2026-04-19',
    humedad: 20,
    altura: 20,
    diametro: 15,
    temp: 22,
    luz: 40,
    ubicacion: 'Semisombra',
    plantada: '2026-04-19',
    diagnosis: [
      { tipo: 'agua', titulo: 'Recién trasplantado', valor: 60, nota: 'Próximo riego en 15 días', sev: 'low' },
      { tipo: 'luz', titulo: 'Semisombra', valor: 40, nota: 'Adaptación post-trasplante', sev: 'mid' },
    ],
    notas: 'Trasplantado el 19/04.',
  },
  {
    id: 7,
    img: 'img/crassula.jpg',
    emoji: '🌿',
    nombre: 'Crassula (árbol del dinero)',
    tipo: 'Suculenta',
    familia: 'Crassulaceae',
    estado: 'trasplantado',
    riegoDias: 18,
    ultimoRiego: '2026-04-20',
    humedad: 18,
    altura: 35,
    diametro: 22,
    temp: 21,
    luz: 80,
    ubicacion: 'Zona soleada',
    plantada: '2022-06-15',
    diagnosis: [
      { tipo: 'agua', titulo: 'Nivel adecuado', valor: 65, nota: 'Próximo riego en 18 días', sev: 'low' },
      { tipo: 'luz', titulo: 'Sol', valor: 80, nota: 'Posición correcta', sev: 'low' },
    ],
    notas: 'Recién trasplantada.',
  },
  {
    id: 8,
    img: 'img/kalanchoe.jpg',
    emoji: '🌺',
    nombre: 'Kalanchoe',
    tipo: 'Suculenta',
    familia: 'Crassulaceae',
    estado: 'floreciendo',
    riegoDias: 10,
    ultimoRiego: '2026-04-20',
    humedad: 35,
    altura: 25,
    diametro: 18,
    temp: 22,
    luz: 80,
    ubicacion: 'Zona soleada',
    plantada: '2024-11-20',
    diagnosis: [
      { tipo: 'agua', titulo: 'Nivel adecuado', valor: 65, nota: 'Próximo riego en 10 días', sev: 'low' },
      { tipo: 'luz', titulo: 'Sol', valor: 80, nota: 'En floración activa', sev: 'low' },
    ],
    notas: 'En plena floración.',
  },
  {
    id: 9,
    img: 'img/rocio.jpg',
    emoji: '✨',
    nombre: 'Rocío (Mesembryanthemum)',
    tipo: 'Suculenta',
    familia: 'Aizoaceae',
    estado: 'floreciendo',
    riegoDias: 10,
    ultimoRiego: '2026-04-20',
    humedad: 20,
    altura: 10,
    diametro: 20,
    temp: 22,
    luz: 95,
    ubicacion: 'Sol pleno',
    plantada: '2024-06-01',
    diagnosis: [
      { tipo: 'agua', titulo: 'Nivel adecuado', valor: 65, nota: 'Próximo riego en 10 días', sev: 'low' },
      { tipo: 'luz', titulo: 'Sol pleno', valor: 95, nota: 'Condiciones ideales', sev: 'low' },
    ],
    notas: 'En plena floración.',
  },
];

const SIEMBRAS_DEFAULT = [
  {
    id: 1,
    img: 'img/albahaca-morada.jpg',
    emoji: '💜',
    nombre: 'Albahaca morada',
    latin: 'Ocimum basilicum',
    fecha: '2026-04-20',
    dias: 0,
    diasGerminar: 10,
    ubicacion: 'Jardinera blanca grande, arcón derecho',
    fase: 'semilla',
  },
  {
    id: 2,
    img: 'img/albahaca-genovesa.jpg',
    emoji: '🌿',
    nombre: 'Albahaca genovesa',
    latin: 'Ocimum basilicum',
    fecha: '2026-04-20',
    dias: 0,
    diasGerminar: 10,
    ubicacion: 'Jardinera barro alargada, arcón derecho',
    fase: 'semilla',
  },
  {
    id: 3,
    img: 'img/cebollino.jpg',
    emoji: '🌱',
    nombre: 'Cebollino',
    latin: 'Allium schoenoprasum',
    fecha: '2026-04-20',
    dias: 0,
    diasGerminar: 12,
    ubicacion: 'Jardinera barro alargada, arcón derecho',
    fase: 'semilla',
  },
  {
    id: 4,
    img: 'img/tomillo.jpg',
    emoji: '🌿',
    nombre: 'Tomillo',
    latin: 'Thymus vulgaris',
    fecha: '2026-04-20',
    dias: 0,
    diasGerminar: 18,
    ubicacion: 'Maceta barro pequeña, arcón derecho',
    fase: 'semilla',
  },
  {
    id: 5,
    img: 'img/eneldo.jpg',
    emoji: '🌿',
    nombre: 'Eneldo',
    latin: 'Anethum graveolens',
    fecha: '2026-04-20',
    dias: 0,
    diasGerminar: 12,
    ubicacion: 'Maceta barro redonda, arcón derecho',
    fase: 'semilla',
  },
  {
    id: 6,
    img: 'img/hierbabuena.jpg',
    emoji: '🌿',
    nombre: 'Hierbabuena',
    latin: 'Mentha spicata',
    fecha: '2026-04-20',
    dias: 0,
    diasGerminar: 9,
    ubicacion: 'Maceta barro grande, rincón izquierdo',
    fase: 'semilla',
  },
  {
    id: 7,
    img: 'img/garden-cress.jpg',
    emoji: '🌱',
    nombre: 'Garden Cress',
    latin: 'Lepidium sativum',
    fecha: '2026-04-20',
    dias: 0,
    diasGerminar: 6,
    ubicacion: 'Maceta barro grande, rincón izquierdo',
    fase: 'semilla',
  },
];

const SIEMBRAS = SIEMBRAS_DEFAULT;

const PENDIENTES = [
  { id: 1, icono: 'IcSprout', texto: 'Separar hijuelos del aloe vera', nota: '' },
  { id: 2, icono: 'IcFlower', texto: 'Sembrar lavanda', nota: 'Maceta barro 28-30cm — sustrato+perlita 50/50' },
  { id: 3, icono: 'IcLeaf', texto: 'Separar espatifilo', nota: 'Ya sin cinta — mover a más luz' },
];

const MAPA_POS = [
  { id: 1, left: '20%', top: '30%' },
  { id: 2, left: '35%', top: '20%' },
  { id: 3, left: '15%', top: '55%' },
  { id: 4, left: '50%', top: '60%' },
  { id: 5, left: '72%', top: '55%' },
  { id: 6, left: '80%', top: '30%' },
  { id: 7, left: '60%', top: '38%' },
  { id: 8, left: '65%', top: '68%' },
  { id: 9, left: '82%', top: '70%' },
];

Object.assign(window, { PLANTAS, SIEMBRAS, SIEMBRAS_DEFAULT, PENDIENTES, MAPA_POS });
