
const HOY = '2026-04-20';

const PLANTAS = [
  {
    id: 1,
    img: 'img/aloe-vera.jpg',
    emoji: '🌵',
    nombre: 'Aloe vera',
    tipo: 'Suculenta',
    familia: 'Asphodelaceae',
    estado: 'bien',
    riegoDias: 14,
    ultimoRiego: '2026-04-15',
    humedad: 28,
    altura: 42,
    diametro: 30,
    temp: 22,
    luz: 85,
    ubicacion: 'Zona sur',
    plantada: '2023-03-10',
    diagnosis: [
      { tipo: 'agua', titulo: 'Nivel de agua correcto', valor: 72, nota: 'Próximo riego en 9 días', sev: 'low' },
      { tipo: 'luz', titulo: 'Luz óptima', valor: 85, nota: 'Mantener posición actual', sev: 'low' },
    ],
    notas: 'Tiene 3 hijuelos listos para separar. Cajón de madera preparado.',
  },
  {
    id: 2,
    img: 'img/crassula-ovata.jpg',
    emoji: '🌿',
    nombre: 'Crassula ovata',
    tipo: 'Suculenta',
    familia: 'Crassulaceae',
    estado: 'atencion',
    riegoDias: 10,
    ultimoRiego: '2026-04-10',
    humedad: 18,
    altura: 35,
    diametro: 22,
    temp: 21,
    luz: 70,
    ubicacion: 'Zona este',
    plantada: '2022-06-15',
    diagnosis: [
      { tipo: 'agua', titulo: 'Riego necesario', valor: 38, nota: 'Sustrato muy seco', sev: 'high' },
      { tipo: 'luz', titulo: 'Luz media', valor: 70, nota: 'Podría ir a zona más soleada', sev: 'mid' },
    ],
    notas: 'Necesita trasplante a maceta un poco más grande. Raíces asomando.',
  },
  {
    id: 3,
    img: 'img/cinta.jpg',
    emoji: '🌱',
    nombre: 'Cinta',
    tipo: 'Herbácea',
    familia: 'Asparagaceae',
    estado: 'bien',
    riegoDias: 7,
    ultimoRiego: '2026-04-17',
    humedad: 55,
    altura: 28,
    diametro: 25,
    temp: 20,
    luz: 45,
    ubicacion: 'Zona norte',
    plantada: '2023-09-01',
    diagnosis: [
      { tipo: 'agua', titulo: 'Humedad adecuada', valor: 68, nota: 'Próximo riego en 4 días', sev: 'low' },
      { tipo: 'luz', titulo: 'Poca luz directa', valor: 45, nota: 'Mover a zona con más luz', sev: 'mid' },
    ],
    notas: 'Espatifilos separados. Tiene varios hijos para propagar.',
  },
  {
    id: 4,
    img: 'img/lavanda.jpg',
    emoji: '💜',
    nombre: 'Lavanda',
    tipo: 'Aromática',
    familia: 'Lamiaceae',
    estado: 'pendiente',
    riegoDias: 5,
    ultimoRiego: '2026-04-18',
    humedad: 40,
    altura: 32,
    diametro: 28,
    temp: 20,
    luz: 90,
    ubicacion: 'Zona sur',
    plantada: '2026-03-15',
    diagnosis: [
      { tipo: 'agua', titulo: 'Agua correcta', valor: 60, nota: 'Próximo riego en 3 días', sev: 'low' },
      { tipo: 'luz', titulo: 'Luz excelente', valor: 90, nota: 'Posición ideal', sev: 'low' },
    ],
    notas: 'Sembrada hace poco. Pendiente de sembrar en maceta 28-30cm con sustrato+perlita 50/50.',
  },
  {
    id: 5,
    img: 'img/kalanchoe.jpg',
    emoji: '🌺',
    nombre: 'Kalanchoe',
    tipo: 'Suculenta',
    familia: 'Crassulaceae',
    estado: 'floreciendo',
    riegoDias: 10,
    ultimoRiego: '2026-04-14',
    humedad: 35,
    altura: 25,
    diametro: 18,
    temp: 22,
    luz: 75,
    ubicacion: 'Zona este',
    plantada: '2024-11-20',
    diagnosis: [
      { tipo: 'agua', titulo: 'Nivel adecuado', valor: 65, nota: 'Próximo riego en 4 días', sev: 'low' },
      { tipo: 'luz', titulo: 'Luz buena', valor: 75, nota: 'En floración activa', sev: 'low' },
    ],
    notas: 'En plena floración. Separar Rocío del Kalanchoe cuando acabe la floración.',
  },
  {
    id: 6,
    img: 'img/phalaenopsis.jpg',
    emoji: '🌸',
    nombre: 'Phalaenopsis',
    tipo: 'Orquídea',
    familia: 'Orchidaceae',
    estado: 'bien',
    riegoDias: 7,
    ultimoRiego: '2026-04-16',
    humedad: 60,
    altura: 45,
    diametro: 20,
    temp: 21,
    luz: 55,
    ubicacion: 'Zona interior',
    plantada: '2024-02-14',
    diagnosis: [
      { tipo: 'agua', titulo: 'Humedad óptima', valor: 74, nota: 'Próximo riego en 3 días', sev: 'low' },
      { tipo: 'luz', titulo: 'Luz filtrada', valor: 55, nota: 'Sin luz directa. Correcto.', sev: 'low' },
    ],
    notas: 'Orquídea pequeña. Unas 900 especies de plantas trepadoras de interior.',
  },
  {
    id: 7,
    img: 'img/monstera.jpg',
    emoji: '🍃',
    nombre: 'Monstera',
    tipo: 'Tropical',
    familia: 'Araceae',
    estado: 'bien',
    riegoDias: 7,
    ultimoRiego: '2026-04-16',
    humedad: 62,
    altura: 80,
    diametro: 45,
    temp: 22,
    luz: 50,
    ubicacion: 'Zona norte',
    plantada: '2023-05-20',
    diagnosis: [
      { tipo: 'agua', titulo: 'Bien hidratada', valor: 78, nota: 'Próximo riego en 3 días', sev: 'low' },
      { tipo: 'luz', titulo: 'Luz indirecta', valor: 50, nota: 'Posición adecuada', sev: 'low' },
    ],
    notas: 'Creciendo bien. Nueva hoja en desarrollo.',
  },
  {
    id: 8,
    img: 'img/tomate-cherry.jpg',
    emoji: '🍅',
    nombre: 'Tomate Cherry',
    tipo: 'Hortaliza',
    familia: 'Solanaceae',
    estado: 'atencion',
    riegoDias: 3,
    ultimoRiego: '2026-04-19',
    humedad: 50,
    altura: 55,
    diametro: 30,
    temp: 21,
    luz: 95,
    ubicacion: 'Zona sur',
    plantada: '2026-03-01',
    diagnosis: [
      { tipo: 'agua', titulo: 'Riego frecuente', valor: 55, nota: 'Riega mañana', sev: 'mid' },
      { tipo: 'luz', titulo: 'Luz plena', valor: 95, nota: 'Condiciones ideales', sev: 'low' },
    ],
    notas: 'Empezando a florecer. Necesita tutor.',
  },
];

const SIEMBRAS_DEFAULT = [
  {
    id: 1,
    img: 'img/lavanda.jpg',
    emoji: '💜',
    nombre: 'Lavanda',
    latin: 'Lavandula angustifolia',
    fecha: '2026-03-15',
    dias: 36,
    diasGerminar: 21,
    ubicacion: 'Semillero interior',
    fase: 'plántula',
  },
  {
    id: 2,
    img: 'img/tomate-cherry.jpg',
    emoji: '🍅',
    nombre: 'Tomate Cherry',
    latin: 'Solanum lycopersicum',
    fecha: '2026-03-01',
    dias: 50,
    diasGerminar: 10,
    ubicacion: 'Semillero terraza',
    fase: 'trasplantado',
  },
  {
    id: 3,
    img: 'img/albahaca.jpg',
    emoji: '🌿',
    nombre: 'Albahaca',
    latin: 'Ocimum basilicum',
    fecha: '2026-04-10',
    dias: 10,
    diasGerminar: 7,
    ubicacion: 'Semillero interior',
    fase: 'germinando',
  },
];

const SIEMBRAS = SIEMBRAS_DEFAULT;

const PENDIENTES = [
  { id: 1, icono: 'IcSprout', texto: 'Separar hijuelos del aloe grande', nota: 'Ya listos en el cajón de madera' },
  { id: 2, icono: 'IcRoot', texto: 'Trasplante Crassula', nota: 'Maceta un poco más grande' },
  { id: 3, icono: 'IcLeaf', texto: 'Separar Espatifilo de la Cinta', nota: 'Mover a más luz' },
  { id: 4, icono: 'IcSprout', texto: 'Sembrar lavanda', nota: 'Maceta 28-30cm — sustrato+perlita 50/50' },
  { id: 5, icono: 'IcFlower', texto: 'Separar Rocío del Kalanchoe', nota: 'Cuando acabe la floración' },
];

const MAPA_POS = [
  { id: 1, left: '72%', top: '60%' },
  { id: 2, left: '55%', top: '72%' },
  { id: 3, left: '15%', top: '25%' },
  { id: 4, left: '80%', top: '30%' },
  { id: 5, left: '60%', top: '45%' },
  { id: 6, left: '20%', top: '60%' },
  { id: 7, left: '10%', top: '45%' },
  { id: 8, left: '82%', top: '55%' },
];

Object.assign(window, { PLANTAS, SIEMBRAS, SIEMBRAS_DEFAULT, PENDIENTES, MAPA_POS });
